sudo: required

services:
  - docker

env:
  globals:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CLOUD_DISABLE_PROMPTS=1
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # decrypt GCP credentials
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  
  # configure GCP
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project weighty-elf-336207
  - gcloud config set compute/zone europe-central2-a
  - gcloud container clusters get-credentials complex-app-cluster

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t amirl1086/complex-client-tests -f ./client/Dockerfile.dev ./client # tests setup

# run tests
script:
  - docker run -e CI=true amirl1086/complex-client-tests npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
